### ISSUE TITLE
Suivi Hackathon DBD2 - Aks?

### ISSUE THREAD

**Issue by daoodaba975** [cheikhcoder/BitChat#1]
Hello @cheikhcoder 

Tu avance bien sur le projet, mais je rencontre un soucis à lancer la conversation....
Aussi sur le `my_app/lib/services/api_key.dart` t'a exposé en claire `ApiKey` essaye en passer par un .env

**Comment by cheikhcoder** [comment]
@daoodaba975 j'ai mis ca sur .env file donc faudra creer ton .env file pour tester

**Comment by daoodaba975** [comment]
Ok d'accord @cheikhcoder

**Comment by daoodaba975** [comment]
@cheikhcoder j'ai encore le même soucis après avoir ajouté mon `API_KEY` dans le fichier .`env`
